name: Upload Git LFS Files to S3

on:
  push:
    branches:
      - main  # Trigger this on pushes to the 'main' branch

jobs:
  upload-lfs-files:
    runs-on: ubuntu-latest  # Use Ubuntu runner
    
    steps:
      # Step 1: Checkout the repository and pull LFS files
      - name: Checkout repository with LFS files
        uses: actions/checkout@v3
        with:
          lfs: true  # Pull all LFS files

      # Step 2: Set up AWS credentials for S3 upload
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Upload LFS files to S3
      - name: Upload LFS files to S3
        run: |
          # Find all LFS-tracked files (e.g., .bin, .zip)
          find . -type f \( -iname \*.bin -o -iname \*.zip \) -exec aws s3 cp {} s3://hyperview-gitlfs/ --storage-class STANDARD_IA \;
          
          echo "LFS files uploaded to S3."

      # Step 4: To clear the local LFS files
      - name: Remove LFS files locally (optional)
        run: |
          git lfs clean
